services:
  - name: finestra-backend
    ports:
      - port: 8080
        http_path: /
    routes:
      - path: /
        port: 8080
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: prod
      - name: DB_URL
        value: jdbc:postgresql://dpg-cvilm6ogjchc73cv893g-a.oregon-postgres.render.com:5432/postgres_7s2c?sslmode=require
      - name: DB_USER
        value: postgres_7s2c_user
      - name: CLOUDINARY_CLOUD_NAME
        value: dtqdhkwsi
      - name: CLOUDINARY_API_KEY
        value: "586611355422232"
    secrets:
      - key: db-password
        name: DB_PASSWORD
      - key: jwt-secret
        name: JWT_SECRET_KEY
      - key: cloudinary-secret
        name: CLOUDINARY_API_SECRET
    build:
      type: dockerfile
    healthchecks:
      http:
        path: /actuator/health
        port: 8080
        interval: 30s
        timeout: 5s
        success_threshold: 1
        failure_threshold: 3